type TemplateContext = {
  name: string;
  idea: string;
  normalized: {
    problem: string;
    domain: string;
    region?: string;
    riskSensitivity: string;
    appType: string;
  };
  classification: {
    kind: string;
    complexity: string;
  };
  copilotInput: string;
  copilotOutput: string;
  decisions: Record<string, any>;
  generatedContent?: Partial<Record<string, string>>;
};

const json = (value: unknown) => JSON.stringify(value, null, 2);

function dependenciesFor(decisions: TemplateContext['decisions']) {
  const deps: Record<string, string> = {};
  if (decisions.framework === 'nextjs') {
    deps.next = '^14.0.0';
    deps.react = '^18.2.0';
    deps['react-dom'] = '^18.2.0';
  } else if (decisions.framework === 'react') {
    deps.react = '^18.2.0';
    deps['react-dom'] = '^18.2.0';
  } else if (decisions.framework === 'express') {
    deps.express = '^4.18.2';
  } else if (decisions.framework === 'fastify') {
    deps.fastify = '^4.28.0';
  }

  if (decisions.database === 'postgres') {
    deps.pg = '^8.11.0';
  } else if (decisions.database === 'mysql') {
    deps.mysql2 = '^3.9.0';
  } else if (decisions.database === 'mongo') {
    deps.mongodb = '^6.3.0';
  } else if (decisions.database === 'sqlite') {
    deps.sqlite3 = '^5.1.6';
  }

  return deps;
}

function scriptsFor(decisions: TemplateContext['decisions']) {
  if (decisions.framework === 'nextjs') {
    return {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      test: 'jest --coverage'
    };
  }

  return {
    build: 'tsc -p tsconfig.json',
    start: 'node dist/index.js',
    dev: 'ts-node src/index.ts',
    test: 'jest --coverage'
  };
}

export function contentFor(path: string, context: TemplateContext) {
  const { name, normalized, classification, copilotInput, copilotOutput, decisions, generatedContent } = context;
  const override = generatedContent?.[path];
  if (override) return override;

  switch (path) {
    case 'README.md': {
      const teamSection = decisions.teamMode
        ? `\n## Team Resources\n- \`docs/onboarding.md\`: New developer onboarding guide\n- \`docs/contribution-guide.md\`: Contribution workflow and standards\n- \`docs/ARCHITECTURE_DECISION_RECORD.md\`: Architecture decisions log\n- \`docs/team-setup.md\`: Team environment and coordination notes\n`
        : '';
      return `# ${name}

${normalized.problem}

## Overview
This repository was generated by **idea2repo**, a CLI that turns product ideas into structured repo scaffolds.

## Detected Profile
- **App type**: ${normalized.appType}
- **Domain**: ${normalized.domain}
- **Risk sensitivity**: ${normalized.riskSensitivity}
- **Complexity**: ${classification.complexity}
- **Framework**: ${decisions.framework ?? 'none'}
- **Database**: ${decisions.database ?? 'none'}

## Getting Started
\`\`\`bash
npm install
npm run build
npm run start
\`\`\`

## What’s Inside
- \`docs/architecture.md\`: Architecture rationale (generated from Copilot CLI)
- \`docs/roadmap.md\`: Phased plan to build the MVP
- \`docs/decisions.md\`: Decision log and tradeoffs
- \`TODO.md\`: Actionable tasks to start building
${teamSection}

## Notes
This scaffold is opinionated and intended to be edited. Use it as a starting point.`;
    }

    case '.gitignore':
      return `node_modules
dist
.env
.idea2repo`;

    case 'package.json':
      return json({
        name,
        version: '0.1.0',
        private: true,
        description: normalized.problem,
        scripts: scriptsFor(decisions),
        dependencies: dependenciesFor(decisions),
        devDependencies: {
          typescript: '^5.1.6',
          'ts-node': '^10.9.1',
          jest: '^29.5.0',
          '@types/jest': '^29.5.0',
          '@types/node': '^18.16.0'
        }
      });

    case 'tsconfig.json':
      return json({
        compilerOptions: {
          target: 'ES2020',
          module: 'commonjs',
          rootDir: 'src',
          outDir: 'dist',
          esModuleInterop: true,
          strict: true
        },
        include: ['src']
      });

    case 'TODO.md':
      return `# TODO (MVP)

## Setup
- [ ] Review \`docs/architecture.md\` and validate the proposed stack
- [ ] Confirm scope for ${classification.complexity} MVP
- [ ] Identify the first user flow to implement

## Build
- [ ] Scaffold core modules for a ${classification.kind} app using ${decisions.framework ?? 'your chosen stack'}
- [ ] Implement data models and interfaces
- [ ] Add basic tests in \`tests/\`

## Iterate
- [ ] Gather feedback and refine requirements
- [ ] Review decision log in \`docs/decisions.md\``;

    case 'docs/architecture.md':
      return `# Architecture

## Copilot CLI Prompt
\`\`\`
${copilotInput}
\`\`\`

## Copilot CLI Response
\`\`\`
${copilotOutput}
\`\`\`

## Summary
- **App type**: ${normalized.appType}
- **Domain**: ${normalized.domain}
- **Risk sensitivity**: ${normalized.riskSensitivity}
- **Complexity**: ${classification.complexity}

## Notes
Use the Copilot rationale above to guide implementation decisions.`;

    case 'docs/roadmap.md':
      return `# Roadmap

## Phase 1 — MVP
- Implement core ${classification.kind} flow
- Establish data model and validation
- Add tests and usage docs

## Phase 2 — Growth
- Improve UX and resilience
- Add analytics and monitoring
- Extend integrations as needed

## Phase 3 — Scale
- Harden security and compliance
- Optimize performance and scalability
- Formalize contribution process`;

    case 'docs/decisions.md':
      return `# Decision Log

## Key Decisions
- **App type**: ${normalized.appType}
- **Domain**: ${normalized.domain}
- **Risk sensitivity**: ${normalized.riskSensitivity}
- **Complexity**: ${classification.complexity}
- **Framework**: ${decisions.framework ?? 'none'}
- **Database**: ${decisions.database ?? 'none'}

## Tradeoffs
Copilot CLI recommended the architecture above. Adjust based on team preferences and constraints.`;

    case 'docs/onboarding.md':
      return `# Onboarding Guide

## Welcome
This project is focused on ${normalized.problem}. You're joining to help ship a ${normalized.appType} experience.

## Getting Started (15 minutes)
1. Install Node.js 18+
2. Clone the repository
3. Run \`npm install\`
4. Copy \`.env.example\` to \`.env\` (if applicable)
5. Run \`npm run dev\`
6. Visit the local app or API endpoint

## Project Structure
- \`/src\` - Application code
- \`/docs\` - Project documentation
- \`/tests\` - Test suite

## Your First Task
Pick a small improvement in \`TODO.md\` and implement it with tests.`;

    case 'docs/contribution-guide.md':
      return `# Contribution Guide

## Branching Strategy
- \`feature/\`: New features
- \`fix/\`: Bug fixes
- \`docs/\`: Documentation updates

## Commit Messages
Use conventional commits (e.g., \`feat:\`, \`fix:\`, \`docs:\`).

## Before Submitting a PR
- [ ] Run \`npm test\`
- [ ] Run \`npm run lint\`
- [ ] Update documentation if needed

## Code Review
Expect at least one reviewer. Share context and screenshots if UI changes are involved.`;

    case 'docs/ARCHITECTURE_DECISION_RECORD.md':
      return `# Architecture Decision Records

## ADR-001: Initial Stack Selection
**Date**: ${new Date().toISOString().split('T')[0]}
**Status**: Accepted

**Context**:
We needed a baseline stack for the ${normalized.appType} project in the ${normalized.domain} domain.

**Decision**:
Use ${decisions.framework ?? 'a framework to be selected'} with ${decisions.database ?? 'a database to be selected'}.

**Reasoning**:
- Matches complexity: ${classification.complexity}
- Aligns with Copilot architecture guidance
- Supports iterative MVP development

**Alternatives Considered**:
- Revisit other frameworks if requirements change

**Consequences**:
- Team will align tooling around the chosen stack.`;

    case 'docs/team-setup.md':
      return `# Team Setup

## Ownership
- Tech Lead: TBD
- Product/Design: TBD
- QA/Testing: TBD

## Environment
- Node.js 18+
- Local environment variables stored in \`.env\`
- Shared secrets stored in the team vault

## Communication
- Daily updates in the team channel
- Weekly planning meeting
- Incident escalation in the on-call channel

## Shared Resources
- Staging URL: TBD
- Analytics dashboard: TBD
- CI/CD pipeline: TBD`;

    case 'tests/main.test.ts':
      return `test('project scaffold', () => {\n  expect('idea2repo').toBeDefined();\n});`;

    case 'src/index.ts':
      return `export function main() {\n  console.log('Hello from ${name}!');\n}\n\nmain();`;

    case 'src/main.ts':
      return `export function run() {\n  return 'start here';\n}\n\nrun();`;

    case 'src/cli.ts':
      return `export function run() {\n  console.log('CLI entrypoint for ${name}');\n}\n\nrun();`;

    case 'src/commands/help.ts':
      return `export function help() {\n  console.log('Available commands: help');\n}`;

    case 'src/server.ts':
      return `import http from 'http';\n\nconst server = http.createServer((_req, res) => {\n  res.writeHead(200, { 'Content-Type': 'application/json' });\n  res.end(JSON.stringify({ status: 'ok' }));\n});\n\nserver.listen(3000, () => {\n  console.log('Server running on http://localhost:3000');\n});`;

    case 'src/routes.ts':
      return `export const routes = [{ method: 'GET', path: '/', handler: 'healthCheck' }];`;

    case 'src/controllers/index.ts':
      return `export function healthCheck() {\n  return { status: 'ok' };\n}`;

    case 'src/App.tsx':
      return `export default function App() {\n  return <main>Welcome to ${name}</main>;\n}\n`;

    case 'src/main.tsx':
      return `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\n\nReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n`;

    case 'src/pages/index.tsx':
      return `export default function Home() {\n  return <div>Home page</div>;\n}\n`;

    case 'src/components/Header.tsx':
      return `export function Header() {\n  return <header>Header</header>;\n}\n`;

    default:
      return `// TODO: Implement ${path}`;
  }
}
