import simpleGit, { SimpleGit } from 'simple-git';
import inquirer from 'inquirer';
import chalk from 'chalk';
import ora from 'ora';
import * as fs from 'fs';
import * as path from 'path';

export interface GitInitOptions {
  projectPath: string;
  projectName: string;
  autoCommit?: boolean;
  autoPush?: boolean;
  remoteName?: string;
  remoteUrl?: string;
}

export class GitManager {
  private git: SimpleGit;
  private projectPath: string;

  constructor(projectPath: string) {
    this.projectPath = projectPath;
    this.git = simpleGit(projectPath);
  }

  static async isGitInstalled(): Promise<boolean> {
    try {
      const git = simpleGit();
      await git.version();
      return true;
    } catch {
      return false;
    }
  }

  async isGitRepo(): Promise<boolean> {
    try {
      await this.git.status();
      return true;
    } catch {
      return false;
    }
  }

  async init(): Promise<void> {
    const spinner = ora('Initializing git repository...').start();

    try {
      await this.git.init();
      spinner.succeed('Git repository initialized');
    } catch (error) {
      spinner.fail('Failed to initialize git repository');
      throw error;
    }
  }

  async createGitignore(): Promise<void> {
    const gitignorePath = path.join(this.projectPath, '.gitignore');

    const gitignoreContent = `# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/
*.log

# Production
build/
dist/
.next/
out/

# Environment
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# idea2repo
.idea2repo/
.idea2repo-conversation.json
`;

    fs.writeFileSync(gitignorePath, gitignoreContent);
  }

  async createInitialCommit(projectName: string): Promise<void> {
    const spinner = ora('Creating initial commit...').start();

    try {
      await this.git.add('.');

      const commitMessage = `🎉 Initial commit: ${projectName}

Generated by idea2repo with GitHub Copilot CLI

Project structure:
- Core application files
- Documentation (README, architecture, roadmap)
- Configuration files
- TODO with MVP tasks
`;

      await this.git.commit(commitMessage);
      spinner.succeed('Initial commit created');
    } catch (error) {
      spinner.fail('Failed to create initial commit');
      throw error;
    }
  }

  async addRemoteAndPush(remoteName: string, remoteUrl: string): Promise<void> {
    const spinner = ora('Adding remote and pushing...').start();

    try {
      await this.git.addRemote(remoteName, remoteUrl);
      const branch = await this.git.revparse(['--abbrev-ref', 'HEAD']);
      await this.git.push(['-u', remoteName, branch]);
      spinner.succeed(`Pushed to ${remoteName}`);
    } catch (error) {
      spinner.fail('Failed to push to remote');
      throw error;
    }
  }

  static async interactiveSetup(options: GitInitOptions): Promise<void> {
    const { projectPath, projectName } = options;
    const manager = new GitManager(projectPath);

    const gitInstalled = await GitManager.isGitInstalled();
    if (!gitInstalled) {
      console.log(chalk.yellow('\n⚠️  Git is not installed. Skipping git setup.\n'));
      return;
    }

    const isRepo = await manager.isGitRepo();
    if (isRepo) {
      console.log(chalk.yellow('\n⚠️  Directory is already a git repository.\n'));
      return;
    }

    const { setupGit } = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'setupGit',
        message: 'Initialize git repository?',
        default: true
      }
    ]);

    if (!setupGit) {
      return;
    }

    await manager.init();
    await manager.createGitignore();

    const { createCommit } = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'createCommit',
        message: 'Create initial commit?',
        default: true
      }
    ]);

    if (createCommit) {
      await manager.createInitialCommit(projectName);
    }

    const { setupRemote } = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'setupRemote',
        message: 'Add GitHub remote and push?',
        default: false
      }
    ]);

    if (setupRemote) {
      const { remoteUrl } = await inquirer.prompt([
        {
          type: 'input',
          name: 'remoteUrl',
          message: 'GitHub repository URL:',
          validate: (input: string) => {
            if (!input) return 'URL is required';
            if (!input.includes('github.com')) return 'Must be a GitHub URL';
            return true;
          }
        }
      ]);

      await manager.addRemoteAndPush('origin', remoteUrl);

      console.log(chalk.green(`\n✨ Repository pushed to ${remoteUrl}\n`));
    }

    console.log(chalk.bold.green('\n✅ Git setup complete!\n'));
  }
}
